### ISSUE TITLE
mfa otp returns "Incorrect secret"

### ISSUE THREAD

**Issue by jurgispods** [limeburst/mfa#2]
I set up a 2FA key, but when running 'mfa otp mykey', I get 

```
Incorrect secret
```

The code I entered is correct, what is going on here?

**Comment by limeburst** [comment]
This project is no longer maintained nor recommended. I've [updated the README](https://github.com/limeburst/mfa/commit/d33c9bd801a4aa7b2c494d3c17fb9933c93e313d) to reflect this.
